# No network or implicit workspace fallback at configure time.
set(LIVOX_RGL_CACHE "${CMAKE_CURRENT_SOURCE_DIR}/.deps/rgl" CACHE PATH
  "Directory prepared by scripts/fetch_dependencies.py")
file(READ "${CMAKE_CURRENT_SOURCE_DIR}/dependencies/lock.json" dependency_lock)
function(require_locked_file relative_path expected_hash)
  set(path "${LIVOX_RGL_CACHE}/${relative_path}")
  if(NOT EXISTS "${path}")
    message(FATAL_ERROR "Missing ${path}. Run python3 scripts/fetch_dependencies.py --cache-dir ${LIVOX_RGL_CACHE}")
  endif()
  file(SHA256 "${path}" actual_hash)
  if(NOT actual_hash STREQUAL expected_hash)
    message(FATAL_ERROR "Checksum mismatch: ${path}. Re-run dependency preparation.")
  endif()
endfunction()
string(JSON artifact_count LENGTH "${dependency_lock}" artifacts)
math(EXPR artifact_last "${artifact_count} - 1")
foreach(index RANGE ${artifact_last})
  string(JSON artifact_path GET "${dependency_lock}" artifacts ${index} path)
  string(JSON artifact_hash GET "${dependency_lock}" artifacts ${index} sha256)
  if(NOT artifact_path MATCHES "^downloads/")
    require_locked_file("${artifact_path}" "${artifact_hash}")
  endif()
endforeach()
foreach(model mid360 avia)
  string(JSON pattern GET "${dependency_lock}" scan_presets ${model} pattern_file)
  string(JSON groups GET "${dependency_lock}" scan_presets ${model} pattern_groups)
  string(JSON rays GET "${dependency_lock}" scan_presets ${model} rays_per_frame)
  if(NOT groups MATCHES "^[1-9][0-9]*$" OR NOT rays MATCHES "^[1-9][0-9]*$")
    message(FATAL_ERROR "Invalid locked pattern layout for ${model}")
  endif()
  math(EXPR expected_size "${groups} * ${rays} * 48")
  file(SIZE "${LIVOX_RGL_CACHE}/patterns/${pattern}" actual_size)
  if(NOT actual_size EQUAL expected_size)
    message(FATAL_ERROR "Pattern file size disagrees with locked layout for ${model}")
  endif()
endforeach()
string(JSON library_path GET "${dependency_lock}" library path)
string(JSON library_hash GET "${dependency_lock}" library sha256)
require_locked_file("${library_path}" "${library_hash}")
add_library(RobotecGPULidar SHARED IMPORTED GLOBAL)
set_target_properties(RobotecGPULidar PROPERTIES
  IMPORTED_LOCATION "${LIVOX_RGL_CACHE}/${library_path}"
  INTERFACE_INCLUDE_DIRECTORIES "${LIVOX_RGL_CACHE}/include")
